spring:
  application:
    name: delivery
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
