spring:
  application:
    name: collector
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
  kafka:
    bootstrap-servers: localhost:9092
kafka:
  topics:
    sensor: telemetry.sensors.v1
    hub: telemetry.hubs.v1
eureka:
  client:
    registerWithEureka: true
    instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    fetch-registry: false
server:
  port: 8080
http:
  balancer:
    api: 'discovery:///main-balancer'